import type { Metadata } from "next";
import { ExaHeader } from "@/components/exa-header";
import { ExaFooter } from "@/components/exa-footer";

export const metadata: Metadata = {
  title: "Privacy & Disclaimer",
  description: "How Exa Vantage handles data, and the limits of its output.",
};

export default function PrivacyPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <ExaHeader />
      <main className="flex-1 pt-14">
        <div className="mx-auto w-full max-w-[760px] px-5 py-12 md:px-6 md:py-16">
          <h1 className="font-heading text-4xl font-bold tracking-tight sm:text-5xl">
            Privacy & Disclaimer
          </h1>

          <div className="mt-8 space-y-8 text-[17px] leading-relaxed text-foreground">
            <section>
              <h2 className="font-heading text-2xl font-semibold">Not investment advice</h2>
              <p className="mt-3 text-muted-foreground">
                Exa Vantage produces informational research summaries generated by
                AI from public web sources. It is not investment, financial,
                legal, or professional advice, and it is not a recommendation to
                buy, sell, or hold any security. Outputs can be incomplete or
                wrong. Verify everything against primary sources before relying
                on it for any decision.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-2xl font-semibold">Firm branding</h2>
              <p className="mt-3 text-muted-foreground">
                The firm names and themes in the picker are used to illustrate a
                branded deliverable. Exa Vantage is an independent demonstration
                and is not affiliated with, endorsed by, or sponsored by any of
                those firms.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-2xl font-semibold">What we collect</h2>
              <p className="mt-3 text-muted-foreground">
                Your search text is sent to our backend to build a report, where
                it is passed to Exa (web search) and Google Gemini (synthesis).
                We use PostHog for privacy-conscious product analytics (page
                views, feature usage, and session replay). We do not ask for or
                store personal information, and reports are generated fresh
                rather than persisted to a database.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-2xl font-semibold">Third parties</h2>
              <p className="mt-3 text-muted-foreground">
                Searches and synthesis are processed by Exa and Google Gemini
                under their respective terms. Analytics are processed by PostHog.
                Hosting is provided by Vercel.
              </p>
            </section>
          </div>
        </div>
      </main>
      <ExaFooter />
    </div>
  );
}
