// Shared domain model for an Exavantage market-intelligence report.

export type ReportMode = "company" | "sector";

/** One company in the discovered universe (a tear sheet). */
export type Company = {
  name: string;
  domain: string;
  /** Sub-segment / cluster this company belongs to (drives the market map). */
  segment: string;
  /** One-line description of what the company does. */
  oneLiner: string;
  /** 2-4 sentence extracted profile. */
  summary: string;
  /** One recent signal (funding, launch, partnership, hiring), if found. */
  recentSignal?: string;
  recentSignalUrl?: string;
  /** 2-3 similar companies (names only) for the "similar to" row. */
  similar: string[];
  /** Whether this company reads as emerging / under-the-radar. */
  emerging: boolean;

  // --- quant (estimated from public web; left blank when not evident) ---
  /** Year founded, e.g. 2019. */
  foundedYear?: number;
  /** Total funding raised, as a human string, e.g. "$120M". */
  funding?: string;
  /** Last/round stage, e.g. "Seed", "Series C", "Public", "Bootstrapped". */
  stage?: string;
  /** Estimated headcount range, e.g. "51-200". */
  employees?: string;
  /** HQ region, e.g. "San Francisco, US". */
  region?: string;
};

/** A market-map cluster: a sub-segment label and the companies inside it. */
export type Segment = {
  label: string;
  /** One-line description of the sub-segment. */
  blurb: string;
  /** Company domains in this cluster (resolve against `companies`). */
  domains: string[];
};

/** A single cited market-context stat, extracted evidence-only from an Exa page.
 *  Blank when no clear figure was found; the number + URL come from Exa, never
 *  invented by the model. */
export type MarketContext = {
  /** Headline figure, e.g. "~$14B market, growing ~11%/yr". */
  stat: string;
  /** Optional one-line elaboration. */
  detail?: string;
  /** Source domain, e.g. "grandviewresearch.com". */
  sourceName: string;
  /** Source URL the figure was extracted from. */
  sourceUrl: string;
  /** How much to trust the source: a recognized research firm vs a secondary page. */
  confidence: "research firm" | "secondary";
};

/** The strategic analysis layer that turns the discovered set into a partner-grade
 *  recommendation. Generated by one Gemini pass, grounded in the companies +
 *  market context. Judgment, not fact: no invented financials. */
export type DealThesis = {
  /** One-sentence verdict / recommendation. */
  recommendation: string;
  conviction: "High" | "Medium" | "Exploratory";
  /** 2-3 catalysts / tailwinds for "why now". */
  whyNow: string[];
  /** Fragmentation evidence sentence, derived from the discovered set. */
  fragmentation: string;
  /** Sub-segments with a consolidation read + an attractiveness rank (1 = best). */
  segmentReads: { label: string; read: string; rank: number }[];
  /** Which sub-segment to start in and why (the beachhead). */
  beachhead: string;
  /** The platform candidate to build around. */
  anchor: { name: string; why: string; brings: string; needs: string };
  /** Tiered targets: tier 1 = call now, 2 = next, 3 = watch. */
  targets: { domain: string; tier: 1 | 2 | 3; whyCall: string; angle: string }[];
  /** 3-4 qualitative value-creation levers (incl. multiple arbitrage). */
  valueLevers: string[];
  /** Off-market -> lower-multiple -> returns logic. */
  edge: string;
  /** 2-3 key risks / what to diligence. */
  risks: string[];
  /** Top names to approach first, with why. */
  firstCalls: { name: string; why: string }[];
  /** One-line sequencing recommendation. */
  sequencing: string;
  /** The concrete decision being requested. */
  ask: string;
  /** Per-slide one-line takeaway conclusions. */
  takeaways: {
    whyNow: string;
    thesis: string;
    where: string;
    anchor: string;
    targets: string;
    value: string;
    edge: string;
    play: string;
  };
};

export type Report = {
  mode: ReportMode;
  /** The restated input: a company name or a sector thesis. */
  query: string;
  /** Company mode only: the resolved anchor company. */
  anchor?: { name: string; domain: string };
  /** Sub-segment clusters for the market map. */
  segments: Segment[];
  /** Every profiled company (tear sheets). */
  companies: Company[];
  /** Under-the-radar subset (also flagged on each company via `emerging`). */
  emerging: Company[];
  /** AI-generated synthesis (shown last on web, first in the PDF). */
  executiveSummary: string;
  /** Cited market-size context (the "size of the prize"). */
  marketContext?: MarketContext;
  /** The partner-grade strategic analysis driving every slide. */
  thesis?: DealThesis;
  /** ISO timestamp set when the report finishes building. */
  generatedAt?: string;
};

// ---- streaming protocol (NDJSON, one JSON object per line) ----

export type StreamEvent =
  | { type: "progress"; phase: string; detail?: string }
  | { type: "meta"; mode: ReportMode; query: string; anchor?: { name: string; domain: string } }
  | { type: "cached"; reportId: string }
  | { type: "market"; marketContext: MarketContext }
  | { type: "segments"; segments: Segment[] }
  | { type: "company"; company: Company }
  | { type: "emerging"; companies: Company[] }
  | { type: "analysis"; thesis: DealThesis }
  | { type: "summary"; executiveSummary: string }
  | { type: "done"; generatedAt: string; reportId?: string }
  | { type: "error"; message: string }
  // Input is clearly not a company or sector (a person, gibberish): stop early
  // with a friendly, on-brand nudge instead of building a nonsense deck.
  | { type: "invalid"; message: string };
